export default [
    {title: "Content creator", colorCode: "#8D353B"},
    {title: "Artist", colorCode: "#8D353B"},
    {title: "Stylist", colorCode: "#8D353B"},
    {title: "Designer", colorCode: "#8D353B"},
    {title: "Musician", colorCode: "#B45F31"},
    {title: "Photographer", colorCode: "#B45F31"},
    {title: "Athlete", colorCode: "#B45F31"},
    {title: "Writer", colorCode: "#B45F31"},
    {title: "Collector", colorCode: "#115F94"},
    {title: "Illustrator", colorCode: "#115F94"},
    {title: "Programmer", colorCode: "#115F94"},
    {title: "Developer", colorCode: "#115F94"},
    {title: "Trader", colorCode: "#115F94"},
]